# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asdgCMatrix_ <- function(XX_) {
    .Call(`_SCRABBLE_asdgCMatrix_`, XX_)
}

mSparse <- function(As, bs) {
    .Call(`_SCRABBLE_mSparse`, As, bs)
}

mMatrix <- function(As, bs) {
    .Call(`_SCRABBLE_mMatrix`, As, bs)
}

mSparseT <- function(As, bs) {
    .Call(`_SCRABBLE_mSparseT`, As, bs)
}

mMatrixT <- function(As, bs) {
    .Call(`_SCRABBLE_mMatrixT`, As, bs)
}

getZ <- function(As, bs) {
    .Call(`_SCRABBLE_getZ`, As, bs)
}

getA <- function(As, betas, gammas, ns) {
    .Call(`_SCRABBLE_getA`, As, betas, gammas, ns)
}

getB <- function(Ds, Zs, Ys, betas) {
    .Call(`_SCRABBLE_getB`, Ds, Zs, Ys, betas)
}

ToDense <- function(newXs) {
    .Call(`_SCRABBLE_ToDense`, newXs)
}

ToSparse <- function(newXs) {
    .Call(`_SCRABBLE_ToSparse`, newXs)
}

cDescent <- function(gamma_Y_B_Lambdas, As, zoness, newXs, nIters, error_thresholds) {
    .Call(`_SCRABBLE_cDescent`, gamma_Y_B_Lambdas, As, zoness, newXs, nIters, error_thresholds)
}

getS <- function(newXs, Lambdas, gammas) {
    .Call(`_SCRABBLE_getS`, newXs, Lambdas, gammas)
}

getY <- function(ss, Us, Vs) {
    .Call(`_SCRABBLE_getY`, ss, Us, Vs)
}

calculateError <- function(Xs, newXs, m1s, n1s) {
    .Call(`_SCRABBLE_calculateError`, Xs, newXs, m1s, n1s)
}

updateLambda <- function(Lambdas, newXs, newYs, gammas) {
    .Call(`_SCRABBLE_updateLambda`, Lambdas, newXs, newYs, gammas)
}

recoverData <- function(newXs) {
    .Call(`_SCRABBLE_recoverData`, newXs)
}

